---
title: "Assessment 1.2"
author: "Kyle Beall"
date: "5/23/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
#install.packages("skimr")
library(skimr)
```

#Data Wrangling

```{r}
#number 3
fast_food<-read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2018/2018-09-04/fastfood_calories.csv")

fast_food%>%skim()
```

```{r}
#number 4
fast_food%>%count(restaurant)

```

```{r}
#number 5
fast_food%>%
  group_by(restaurant)%>%
  summarise(average_calories=mean(calories))%>%
  ungroup()

#number 6
fast_food<-
  fast_food%>%
  group_by(restaurant)%>%
  mutate(average_calories=mean(calories))%>%
  ungroup()

```

```{r}
#number 7
fast_food$restaurant<-as_factor(fast_food$restaurant)

class(fast_food$restaurant)

fast_food%>%
  ggplot(
    aes(total_fat)
  )+
  geom_histogram()+
  facet_wrap(vars(restaurant))
```

Above we have a series of histograms displaying `total_fat` found in each type of `restaurant`. Side by side, we can get a good idea of how each restaurant compares to each other in terms of how much fat their food's contain. For example, we can see from these graphs that Chic Fil-A, overall, offers food with the least amount of total fat.

```{r}
#number 8
fast_food%>%count(restaurant)

```

```{r}
#number 9
fast_food<-fast_food%>%
  group_by(restaurant)%>%
  mutate(max_total_fat=max(total_fat))%>%
  ungroup

```

```{r}
#number 10
fast_food%>%
  group_by(restaurant=="Mcdonalds")%>%
  ggplot(
    aes(sugar, protein)
  )+
  geom_point()

```